# Generated by Django 5.2.12 on 2026-04-10 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisory_system', '0002_alter_diseasedetection_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yieldprediction',
            name='area',
            field=models.CharField(max_length=100),
        ),
    ]
