# Generated by Django 5.2.12 on 2026-04-15 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advisory_system', '0005_profile_is_verified_profile_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='otp',
        ),
    ]
